'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18331
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AOE2_Sound_Board_OS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\01 Yes.mp3.
        '''</summary>
        Friend ReadOnly Property _01_Yes() As String
            Get
                Return ResourceManager.GetString("_01_Yes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\02 No.mp3.
        '''</summary>
        Friend ReadOnly Property _02_No() As String
            Get
                Return ResourceManager.GetString("_02_No", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\03 Food, please.mp3.
        '''</summary>
        Friend ReadOnly Property _03_Food__please() As String
            Get
                Return ResourceManager.GetString("_03_Food__please", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\04 Wood, please.mp3.
        '''</summary>
        Friend ReadOnly Property _04_Wood__please() As String
            Get
                Return ResourceManager.GetString("_04_Wood__please", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\05 Gold, PLease.mp3.
        '''</summary>
        Friend ReadOnly Property _05_Gold__PLease() As String
            Get
                Return ResourceManager.GetString("_05_Gold__PLease", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\06 Stone, please.mp3.
        '''</summary>
        Friend ReadOnly Property _06_Stone__please() As String
            Get
                Return ResourceManager.GetString("_06_Stone__please", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\07 Ahh.mp3.
        '''</summary>
        Friend ReadOnly Property _07_Ahh() As String
            Get
                Return ResourceManager.GetString("_07_Ahh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\08 All hail.mp3.
        '''</summary>
        Friend ReadOnly Property _08_All_hail() As String
            Get
                Return ResourceManager.GetString("_08_All_hail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\09 Oooh.mp3.
        '''</summary>
        Friend ReadOnly Property _09_Oooh() As String
            Get
                Return ResourceManager.GetString("_09_Oooh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\10 Back to Age 1.mp3.
        '''</summary>
        Friend ReadOnly Property _10_Back_to_Age_1() As String
            Get
                Return ResourceManager.GetString("_10_Back_to_Age_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\11 Herb laugh.mp3.
        '''</summary>
        Friend ReadOnly Property _11_Herb_laugh() As String
            Get
                Return ResourceManager.GetString("_11_Herb_laugh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\12 Being rushed.mp3.
        '''</summary>
        Friend ReadOnly Property _12_Being_rushed() As String
            Get
                Return ResourceManager.GetString("_12_Being_rushed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\13 Blame your isp.mp3.
        '''</summary>
        Friend ReadOnly Property _13_Blame_your_isp() As String
            Get
                Return ResourceManager.GetString("_13_Blame_your_isp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\14 Start the game.mp3.
        '''</summary>
        Friend ReadOnly Property _14_Start_the_game() As String
            Get
                Return ResourceManager.GetString("_14_Start_the_game", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\15 Don&apos;t Point That Thing.mp3.
        '''</summary>
        Friend ReadOnly Property _15_Don_t_Point_That_Thing() As String
            Get
                Return ResourceManager.GetString("_15_Don_t_Point_That_Thing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\16 Enemy Sighted.mp3.
        '''</summary>
        Friend ReadOnly Property _16_Enemy_Sighted() As String
            Get
                Return ResourceManager.GetString("_16_Enemy_Sighted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\17 It Is Good.mp3.
        '''</summary>
        Friend ReadOnly Property _17_It_Is_Good() As String
            Get
                Return ResourceManager.GetString("_17_It_Is_Good", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\18 I Need a Monk.mp3.
        '''</summary>
        Friend ReadOnly Property _18_I_Need_a_Monk() As String
            Get
                Return ResourceManager.GetString("_18_I_Need_a_Monk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\19 Long Time No Siege.mp3.
        '''</summary>
        Friend ReadOnly Property _19_Long_Time_No_Siege() As String
            Get
                Return ResourceManager.GetString("_19_Long_Time_No_Siege", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\20 My granny.mp3.
        '''</summary>
        Friend ReadOnly Property _20_My_granny() As String
            Get
                Return ResourceManager.GetString("_20_My_granny", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\21 Nice Town I&apos;ll Take It.mp3.
        '''</summary>
        Friend ReadOnly Property _21_Nice_Town_I_ll_Take_It() As String
            Get
                Return ResourceManager.GetString("_21_Nice_Town_I_ll_Take_It", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\22 Quit Touchin.mp3.
        '''</summary>
        Friend ReadOnly Property _22_Quit_Touchin() As String
            Get
                Return ResourceManager.GetString("_22_Quit_Touchin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\23 Raiding Party.mp3.
        '''</summary>
        Friend ReadOnly Property _23_Raiding_Party() As String
            Get
                Return ResourceManager.GetString("_23_Raiding_Party", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\24 Dadgum.mp3.
        '''</summary>
        Friend ReadOnly Property _24_Dadgum() As String
            Get
                Return ResourceManager.GetString("_24_Dadgum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\25 Smite Me.mp3.
        '''</summary>
        Friend ReadOnly Property _25_Smite_Me() As String
            Get
                Return ResourceManager.GetString("_25_Smite_Me", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\26 The wonder.mp3.
        '''</summary>
        Friend ReadOnly Property _26_The_wonder() As String
            Get
                Return ResourceManager.GetString("_26_The_wonder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\27 You play 2 hours.mp3.
        '''</summary>
        Friend ReadOnly Property _27_You_play_2_hours() As String
            Get
                Return ResourceManager.GetString("_27_You_play_2_hours", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\28 You Should See the Other Guy.mp3.
        '''</summary>
        Friend ReadOnly Property _28_You_Should_See_the_Other_Guy() As String
            Get
                Return ResourceManager.GetString("_28_You_Should_See_the_Other_Guy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\29 Roggan.mp3.
        '''</summary>
        Friend ReadOnly Property _29_Roggan() As String
            Get
                Return ResourceManager.GetString("_29_Roggan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to taunt\30 Wololo.mp3.
        '''</summary>
        Friend ReadOnly Property _30_Wololo() As String
            Get
                Return ResourceManager.GetString("_30_Wololo", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
